### ISSUE TITLE
doesn't work on Debian based system(Pop OS)

### ISSUE THREAD

**Issue by ghost** [phisch/giph#11]
So I tried to build the program from source
that part worked. However what doesn't work is actually using it

I use Gnome so it might be an issue related to that DE
it would be awesome if I'd be able to use said program on my system

**Comment by ghost** [comment]
when trying the example command  giph -s -l -c 1,1,1,0.3 -b 5 -p -5 out.gif 

I get this error message
/usr/bin/giph: line 272: slop: command not found
2020-08-27 20:04:17: ERROR: could not parse geometry string ''

**Comment by ghifarit53** [comment]
Of course, it's because `slop` isn't available in your system.
I'm also on Ubuntu, which is the base of Pop OS
run `sudo apt install slop` to get it

**Comment by phisch** [comment]
@MightyPrince1 make sure you install the dependencies listed in the `from source` installation instructions: https://github.com/phisch/giph#from-source

Closing the issue, just comment if this still is an issue.
