### ISSUE TITLE
Selection color always white

### ISSUE THREAD

**Issue by GideonWolfe** [phisch/giph#12]
First of all, this program is awesome and I already have a few nifty scripts built around it.

I am trying to replicate the gif on the example using the `-c` flag, but every color I enter makes the `slop` selection window entirely white. 

I am using Arch + i3. Is this something I have to set up within `slop`, like the shaders?

Edit: Hmm, it seems to work if I do `-c 0.0,0.0,0.0`, which gives black. I somehow need to get all the colors in my scheme into a FLOAT FLOAT FLOAT format...

**Comment by phisch** [comment]
@GideonWolfe those values are just passed through to slop (https://github.com/naelstrof/slop).
They are floating point values between 0 and 1.
Here is a website you can use to convert RGB hex colors to RGB normalized decimal values: https://doc.instantreality.org/tools/color_calculator

Basically: FF (hex) = 255 (dec) -> 255 / 255 = 1 (normalized decimal)

Hope that helps!

**Comment by GideonWolfe** [comment]
Thanks, I'm just gonna write a script to dynamically do this conversion for me so I can change theme on the fly :)

**Comment by GideonWolfe** [comment]
If anyone comes across this later, I whipped this up to yank some specified color `0-15` from a chached `pywal` template containing all of the color variables in standard RGB `int,int,int`.

It then outputs this color in `float,float,float`. It can be modified to be hardcoded with one color, or to search for another wal color.

```bash
#!/bin/bash

# Takes in a color number, finds the color stored in (int, int, int) and converts it to (float, float, float)

COLORNUM=$1

# Find the color code corresponding to the desired color
INTCODE=$(cat $HOME/.cache/wal/wal_rgb_colors | grep color$COLORNUM | cut -d' ' -f2-) 

# Read these regular INT rgb values into an array
IFS=', ' read -r -a array <<< "$INTCODE"
INTONE="${array[0]}"
INTTWO="${array[1]}"
INTTHREE="${array[2]}"

# Calculate and format the RGB values into decimals
FLOATONE=$( echo "scale=2; $INTONE / 255" | bc -l | sed 's/^\./0./')
FLOATTWO=$( echo "scale=2; $INTTWO / 255" | bc -l | sed 's/^\./0./')
FLOATTHREE=$( echo "scale=2; $INTTHREE / 255" | bc -l | sed 's/^\./0./')
echo $FLOATONE,$FLOATTWO,$FLOATTHREE
```
