### ISSUE TITLE
giph --stop doesn't seem to work

### ISSUE THREAD

**Issue by Barbaross93** [phisch/giph#15]
Hello

I'm currently doing recordings using the command `giph -s -y ~/Pictures/Gifs/Recordings/$(date +%s).gif`. It starts fine, but when I try to use `giph --stop` in another terminal to terminate the recording, nothing happens. Looking at the source code, it looks like you use `pgrep giph` to determine if the process is running. When I run that directly in the terminal, nothing comes up. It looks like the actual process name is `bash` when I look in `htop`. So when I use `pgrep -f giph`, I get a process id. Adding that flag in the source code (the `stop_all_recordings` function) seems to work. My shell is zsh, which is what I suspect is the reason why this happens.

**Comment by phisch** [comment]
Thanks for the report!

This is now fixed in #16. It now matches all bash processes that run giph. Only running `pgrep -f giph` could accidentally terminate processes that contain `giph` anywhere in their command.
